/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Heatmap */
        get: operations["get_heatmap_v1_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Presets */
        get: operations["get_presets_v1_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score Point */
        post: operations["score_point_v1_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/score/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score Batch */
        post: operations["score_batch_v1_score_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchScoreRequest */
        BatchScoreRequest: {
            /** Points */
            points: components["schemas"]["Point"][];
            /**
             * Preset
             * @default warehouse
             * @enum {string}
             */
            preset: "warehouse" | "retail" | "ev";
            /** Weights */
            weights?: {
                [key: string]: number;
            } | null;
        };
        /** BatchScoreResponse */
        BatchScoreResponse: {
            /** Results */
            results: components["schemas"]["ScoreResponse"][];
        };
        /** ConstraintResult */
        ConstraintResult: {
            /** Actual */
            actual: unknown;
            /** Id */
            id: string;
            /**
             * Label
             * @default
             */
            label: string;
            /** Pass */
            pass: boolean;
            /** Required */
            required: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeatmapCell
         * @description One heatmap cell: identity + weight-independent subscores only.
         *
         *     No composite score, no geometry — the frontend derives boundaries
         *     with h3-js and recomputes the weighted composite locally.
         */
        HeatmapCell: {
            /** Eligible */
            eligible: boolean;
            /** H3Index */
            h3Index: string;
            subscores: components["schemas"]["Subscores"];
        };
        /** HeatmapResponse */
        HeatmapResponse: {
            /** Cells */
            cells: components["schemas"]["HeatmapCell"][];
            /** Datasetid */
            datasetId: string;
            /** H3Resolution */
            h3Resolution: number;
            /**
             * Preset
             * @enum {string}
             */
            preset: "warehouse" | "retail" | "ev";
        };
        /** Point */
        Point: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** ScoreRequest */
        ScoreRequest: {
            point: components["schemas"]["Point"];
            /**
             * Preset
             * @default warehouse
             * @enum {string}
             */
            preset: "warehouse" | "retail" | "ev";
            /** Weights */
            weights?: {
                [key: string]: number;
            } | null;
        };
        /** ScoreResponse */
        ScoreResponse: {
            /** Constraints */
            constraints: components["schemas"]["ConstraintResult"][];
            /** Eligible */
            eligible: boolean;
            /** H3 Index */
            h3_index: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Score */
            score: number;
            subscores: components["schemas"]["Subscores"];
        };
        /** Subscores */
        Subscores: {
            /** Aqi */
            aqi: number;
            /** Demographics */
            demographics: number;
            /** Flood */
            flood: number;
            /** Poi */
            poi: number;
            /** Transport */
            transport: number;
            /** Zoning */
            zoning: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_heatmap_v1_heatmap_get: {
        parameters: {
            query?: {
                preset?: "warehouse" | "retail" | "ev";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_presets_v1_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: number;
                        };
                    };
                };
            };
        };
    };
    score_point_v1_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_batch_v1_score_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
